---
sidebar: sidebar
permalink: concept-digital-wallet.html
keywords: digital wallet, bluexp digital wallet, licensing, licenses, services, supported services
summary: "The BlueXP digital wallet enables you to manage and monitor BlueXP licenses purchased from NetApp (BYOL), BlueXP marketplace subscriptions, and NetApp Keystone."
---

= Learn about the BlueXP digital wallet
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The BlueXP digital wallet enables you to manage and monitor BlueXP licenses purchased from NetApp (BYOL), BlueXP marketplace subscriptions, and NetApp Keystone.

== Features

* Manage capacity-based and node-based licenses for Cloud Volumes ONTAP
* Add and manage licenses for BlueXP data services
* Manage subscriptions for PAYGO and annual contracts associated with your BlueXP account and with Astra Control
* Manage Keystone Subscription services for use with Cloud Volumes ONTAP and on-premises ONTAP clusters, and request changes to committed capacity
* View hardware and software contract status information for on-premises ONTAP clusters

== Supported services

The BlueXP digital wallet enables you to manage licenses for the following services:

* https://docs.netapp.com/us-en/bluexp-backup-recovery/index.html[Backup and recovery^]
* https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/index.html[Cloud Volumes ONTAP^]
* https://docs.netapp.com/us-en/bluexp-disaster-recovery/index.html[Disaster recovery^] (BYOL only)
* https://docs.netapp.com/us-en/bluexp-ransomware-protection/index.html[Ransomware protection^]
* https://docs.netapp.com/us-en/bluexp-ontap-onprem/index.html[On-prem ONTAP clusters^]
* https://docs.netapp.com/us-en/bluexp-tiering/index.html[Tiering^]

TIP: The BlueXP digital wallet also enables you to manage licenses for BlueXP classification. However, BlueXP classification is now available as a core capability within BlueXP at no additional charge. A license or subscription is no longer required.