---
sidebar: sidebar
permalink: concept-digital-wallet.html
keywords: digital wallet, bluexp digital wallet, licensing, licenses, services, supported services
summary: The BlueXP digital wallet enables you to manage and monitor licenses and subscriptions for storage services, data services, and NetApp Keystone.
---

= BlueXP digital wallet overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/media/

[.lead]
The BlueXP digital wallet enables you to manage and monitor licenses and subscriptions for storage services, data services, and NetApp Keystone.

== Features

* Manage capacity-based and node-based licenses for Cloud Volumes ONTAP
* Add and manage licenses for BlueXP data services
* Manage BlueXP subscriptions for PAYGO and annual contracts
* Manage Keystone Flex Subscriptions for use with Cloud Volumes ONTAP and request changes to committed capacity
* View hardware and software contract status information for on-premises ONTAP clusters

== Supported services

The BlueXP digital wallet enables you to manage licensing for the following:

* Cloud Backup
* Cloud Data Sense
* Cloud Tiering
* Cloud Volumes ONTAP
* On-prem ONTAP clusters