---
sidebar: sidebar
permalink: concept-digital-wallet.html
keywords: digital wallet, bluexp digital wallet, licensing, licenses, services, supported services
summary: "The BlueXP digital wallet enables you to manage and monitor BlueXP licenses purchased from NetApp (BYOL), BlueXP marketplace subscriptions, and NetApp Keystone."
---

= Learn about the BlueXP digital wallet
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The BlueXP digital wallet enables you to manage and monitor BlueXP licenses purchased from NetApp (BYOL), BlueXP data services marketplace subscriptions (including NetApp Cloud Volumes ONTAP), and NetApp Keystone.

== How licenses and subscriptions are displayed in digital wallet

Both licenses and subscriptions automatically display in digital wallet when the BlueXP account used to subscribe is also an NetApp Support Site account. If you used a BlueXP account that is not associated with your NetApp Support Site (NSS) account, you'll need to manually add and update licenses and you won't see usage, capacity, and other details change.

NOTE: You need to have deployed a Connector in order to view subscription information in digital wallet. A Connector is also needed to view node licenses for Cloud Volumes ONTAP.

In the meantime, BlueXP automatically queries NetApp's licensing service to obtain details about the licenses associated with your NetApp Support Site account. If there are no errors, BlueXP automatically adds the licenses to the digital wallet.

If BlueXP can't add the license, you'll need to manually add it to the digital wallet yourself. For example, if your BlueXP user account is not associated with your NetApp Support Site account, you'll need to add the licenses yourself. 

After you purchase a license from your NetApp sales representative, NetApp sends you an email with the serial number and additional licensing details. You'll need that serial number to add or update the respective license in digital wallet.

https://docs.netapp.com/us-en/bluexp-setup-admin/task-adding-nss-accounts.html[Learn how to add your NetApp Support Site account to BlueXP user credentials^].

== Supported services

The BlueXP digital wallet enables you to manage licenses and subscriptions for the following services:

* https://docs.netapp.com/us-en/bluexp-backup-recovery/index.html[Backup and recovery^]
* https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/index.html[Cloud Volumes ONTAP^]
* https://docs.netapp.com/us-en/bluexp-disaster-recovery/index.html[Disaster recovery^] (BYOL only)
* https://docs.netapp.com/us-en/bluexp-ransomware-protection/index.html[Ransomware protection^]
* https://docs.netapp.com/us-en/bluexp-ontap-onprem/index.html[On-prem ONTAP clusters^]
* https://docs.netapp.com/us-en/bluexp-tiering/index.html[Tiering^]





