settings:
  name: "BlueXP digital wallet"
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true

sidebar:
  entries:
    - title: BlueXP digital wallet docs
      url: /index.html
    - title: Release notes
      entries:
        - title: What's new
          url: /whats-new.html
    - title: Get started
      entries:
        - title: Learn about the BlueXP digital wallet
          url: /concept-digital-wallet.html
    - title: Use the BlueXP digital wallet
      entries:
    - title: Use the Overview dashboard
      url: /task-homepage.html
    - title: Manage licenses
      entries:
        - title: Manage data service licenses
          url: /task-manage-data-services-licenses.html
        - title: Manage licenses for Cloud Volumes ONTAP
          entries:
            - title: Capacity-based licenses for Cloud Volumes ONTAP
              url: /task-manage-capacity-licenses.html
            - title: Node-based licenses for Cloud Volumes ONTAP
              url: /task-manage-node-based-licenses.html
    - title: Manage Marketplace subscriptions
      url: /task-manage-subscriptions.html
    - title: Manage Keystone subscriptions
      url: /task-manage-keystone.html
    - title: Manage licenses for on-premises ONTAP 
      url: /task-manage-on-prem-clusters.html
    - title: Knowledge and support

      entries:
        - title: Register for support
          url: /task-support-registration.html
        - title: Get help
          url: /task-get-help.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: BlueXP
  repo: bluexp-family
