settings:
  name: "BlueXP digital wallet"
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
sidebar:
  entries:
    - title: BlueXP digital wallet docs
      url: /index.html
    - title: Release notes
      url: /whats-new.html
    - title: Get started
      entries:
        - title: Learn about the BlueXP digital wallet
          url: /concept-digital-wallet.html
    - title: Use the BlueXP digital wallet
      entries:
        - title: Manage licenses for Cloud Volumes ONTAP
          entries:
            - title: Capacity-based licenses
              url: /task-manage-capacity-licenses.html
            - title: Node-based licenses
              url: /task-manage-node-based-licenses.html
        - title: Manage licenses for BlueXP data services
          url: /task-manage-data-services-licenses.html
        - title: Manage PAYGO subscriptions and contracts
          url: /task-manage-subscriptions.html
        - title: Manage Keystone Subscription services
          url: /task-manage-keystone.html
        - title: Manage licenses for on-prem ONTAP clusters
          url: /task-manage-on-prem-clusters.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /task-support-registration.html
        - title: Get help
          url: /task-get-help.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: BlueXP
  repo: cloud-manager-family
  sidebar_label: All BlueXP documentation
homepage:
  tiles:
    - title: Get started
      links:
        - title: Learn about the BlueXP digital wallet
          url: concept-digital-wallet.html
    - title: Manage your licenses
      links:
        - title: Manage capacity-based licenses for Cloud Volumes ONTAP
          url: task-manage-capacity-licenses.html
        - title: Manage licenses for BlueXP data services
          url: task-manage-data-services-licenses.html
        - title: Manage PAYGO subscriptions and contracts
          url: task-manage-subscriptions.html
    - title: Blogs & community
      links:
        - title: NetApp Community
          url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
        - title: BlueXP blog
          url: https://bluexp.netapp.com/blog
        - title: Cloud webinars
          url: https://bluexp.netapp.com/events