---
sidebar: sidebar
permalink: task-manage-data-services-licenses.html
keywords: data services, byol, cloud backup, cloud tiering, data sense, cloud data sense, obtain license file, nlf, add license, update license, digital wallet, bluexp digital wallet, classification, bluexp classification, bluexp tiering, tiering, bluexp backup and recovery, backup and recovery, disaster recovery
summary: "The BlueXP digital wallet enables you to manage licenses that you purchased directly from NetApp (BYOL) for use with BlueXP backup and recovery, disaster recovery, and tiering. You can view used license capacity, how much free capacity you have left, and you'll see notifications if you reached the capacity limit or the expiration date."
---

= Manage licenses for BlueXP data services
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The BlueXP digital wallet enables you to manage licenses that you purchased directly from NetApp (BYOL) for use with BlueXP data services, including Cloud Volumes for ONTAP. You can view used license capacity, how much free capacity you have left, and you'll see notifications if you reached the capacity limit or the expiration date.

NOTE: The *Data service licenses* page lists all licenses. If you want license details for a specific data service, use the data service tiles on the *Overview* dashboard. link:task-homepage.html#overview-page[Learn more about the Overview dashboard].

The instructions on this page provide information that applies to each service. For more specific information about the licensing for these services, refer to the following pages:

* https://docs.netapp.com/us-en/bluexp-backup-recovery/task-licensing-cloud-backup.html[Set up licensing for BlueXP backup and recovery^]
* https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html[Set up licensing for BlueXP disaster recovery^]
* https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-licenses.html[Set up licensing for BlueXP ransomware protection^]
* https://docs.netapp.com/us-en/bluexp-tiering/task-licensing-cloud-tiering.html[Set up licensing for BlueXP tiering^]
*  https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html[Set up licensing for Cloud Volumes ONTAP^]


== Obtain a license file

include::_include/task-obtain-license.adoc[]

== Add a license

include::_include/task-add-license.adoc[]


== Update a license

include::_include/task-update-license.adoc[]


