
The BlueXP digital wallet has been redesigned for ease of use and now provides additional subscription and license management directly from digital wallet.

=== Home page changes
The digital wallet homepage now provides a graphical view of all of your NetApp licenses and Marketplace subscriptions, with the ability to drill-down into specific services, license types and required actions.

=== Configuring subscriptions to credentials
The BlueXP digital wallet now allows you to configure your subscriptions to provider credentials. Typically you do this when you first subscribe to a Marketplace subscription or annual contract. Previously changing the subscription's credentials could only be done on the Credentials page. 

=== Associating subscriptions with organizations
You can now update the organization to which a subscription is associated directly from digital wallet.

=== Managing Cloud Volume ONTAP licenses
You now manage Cloud Volumes ONTAP licenses through the home page or the *Data service licenses tab*. Cloud Volumes ONTAP information can be viewed from the home page of digital wallet and its own data screen. You can manage Cloud Volumes ONTAP license files from the Data service licenses tab, and use the Marketplace subscriptions tab to view your subscription information.
